version: '3.4'

services:
  superbodega.api:
    image: ${DOCKER_REGISTRY-}superbodegaapi
    build:
      context: .
      dockerfile: SuperBodega.API/Dockerfile
    depends_on:
      - db
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=SuperBodega;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
    ports:
      - "8000:80"
      - "8001:443"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - superbodega-data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  superbodega-data:
  rabbitmq-data: